# Generated by Django 5.2.4 on 2025-07-10 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('street_name', models.CharField(max_length=100)),
                ('house_number', models.IntegerField()),
                ('postcode', models.IntegerField()),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
        ),
    ]
