# Generated by Django 5.2.4 on 2025-07-10 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.CharField(default='default', max_length=100),
            preserve_default=False,
        ),
    ]
