# Generated by Django 5.2.4 on 2025-07-11 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0002_address_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='profile_picture',
        ),
    ]
