# Generated by Django 5.2.4 on 2025-07-14 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0003_remove_address_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='house_number',
            field=models.CharField(max_length=50),
        ),
    ]
