# Generated by Django 5.2.4 on 2025-07-14 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0004_alter_address_house_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
