# Generated by Django 5.2.4 on 2025-07-15 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0005_address_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
