# Generated by Django 5.2.4 on 2025-07-15 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0007_alter_address_city_alter_address_house_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='postcode',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
