# Generated by Django 5.2.4 on 2025-07-16 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0008_alter_address_postcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
    ]
