# Generated by Django 5.2.4 on 2025-07-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0009_alter_address_first_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='first_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterUniqueTogether(
            name='address',
            unique_together={('first_name', 'last_name', 'city', 'street_name', 'house_number', 'postcode')},
        ),
    ]
