# Generated by Django 5.2.4 on 2025-07-17 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('addressbook', '0010_alter_address_first_name_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='address',
            unique_together=set(),
        ),
    ]
